### PR TITLE
fix a bug of undefined Alphabet.toks

### PR DESCRIPTION
**Pull request by cutecutecat**
Fix error attribute 'toks' into 'standard_toks'

```Traceback (most recent call last):
  File "/home/xxx/test_esm.py", line 11, in <module>
    print(model_alphabet.to_dict())
  File "/home/xxx/anaconda3/envs/fasthit/lib/python3.9/site-packages/fair_esm-0.3.1-py3.9.egg/esm/data.py", line 129, in to_dict
AttributeError: 'Alphabet' object has no attribute 'toks'
```

### CODE REVIEW

**Comment by tomsercu** [comment]
Thanks for finding this and submitting a fix!
But actually this method doesn't make too much sense and isn't used in the codebase, maybe you could instead replace it with returning the token to idx mapping:
`return self.tok_to_idx.copy()`
Thx!

**Comment by cutecutecat** [comment]
> Thanks for finding this and submitting a fix!
> But actually this method doesn't make too much sense and isn't used in the codebase, maybe you could instead replace it with returning the token to idx mapping:
> `return self.tok_to_idx.copy()`
> Thx!

Thank you for your review！
As I see, `self.tok_to_idx` is a map from `all_toks`, which equals `prepend_toks`+`standard_toks`.
If we use `self.tok_to_idx` in `to_dict`, than ` from_dict`  can no longer get `standard_toks`. Therefore, it cannot work any more. 
I have searched in the project and ensured there is nowhere require `Alphabet.from_dict`.
If `from_dict` is also deprecated as well? Can I remove `from_dict` together?

**Comment by tomsercu** [comment]
Ah now I see where you're coming from - yes you can remove both! Thank you!

**Review by tomsercu — APPROVED** [review]
lgtm!

**Pull request merged**
